version: "3.8"
services:
  corretora-app-database:
    container_name: corretora-app-database
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWD}
      - MYSQL_DATABASE=${MYSQL_DB}
    ports:
      - '${MYSQL_PORT}:3306'
    networks:
      - backend
    volumes:
      - mysql-corretora-data:/var/libs/mysql
 
volumes:
  mysql-corretora-data:
networks:
  backend: