name: User Story
description: Crie sua história de usuário
title: "[User-Story]: "
labels: ["bug", "triage"]
assignees:
  - GuilhermeAGouveia
body:
  - type: textarea
    id: describe
    attributes:
      label: Descrição
      description: Dê a descrição de sua histório utilizando o formato Como ..., eu quero ... para ...
      placeholder: Tell us what you see!
      value: "Como [YOUR_ROLE], </br> eu quero [SOMETHING] </br> para [FINALITY]"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de Aceitação
      description: Forneça seus critérios de aceitação
      value: |
        - [] 
        - []
        - []
      render: bash
    validations:
      required: true

